// MP3_PC_mm_interconnect_1.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 18.0 614

`timescale 1 ps / 1 ps
module MP3_PC_mm_interconnect_1 (
		input  wire [11:0] HPS_h2f_lw_axi_master_awid,                                        //                                       HPS_h2f_lw_axi_master.awid
		input  wire [20:0] HPS_h2f_lw_axi_master_awaddr,                                      //                                                            .awaddr
		input  wire [3:0]  HPS_h2f_lw_axi_master_awlen,                                       //                                                            .awlen
		input  wire [2:0]  HPS_h2f_lw_axi_master_awsize,                                      //                                                            .awsize
		input  wire [1:0]  HPS_h2f_lw_axi_master_awburst,                                     //                                                            .awburst
		input  wire [1:0]  HPS_h2f_lw_axi_master_awlock,                                      //                                                            .awlock
		input  wire [3:0]  HPS_h2f_lw_axi_master_awcache,                                     //                                                            .awcache
		input  wire [2:0]  HPS_h2f_lw_axi_master_awprot,                                      //                                                            .awprot
		input  wire        HPS_h2f_lw_axi_master_awvalid,                                     //                                                            .awvalid
		output wire        HPS_h2f_lw_axi_master_awready,                                     //                                                            .awready
		input  wire [11:0] HPS_h2f_lw_axi_master_wid,                                         //                                                            .wid
		input  wire [31:0] HPS_h2f_lw_axi_master_wdata,                                       //                                                            .wdata
		input  wire [3:0]  HPS_h2f_lw_axi_master_wstrb,                                       //                                                            .wstrb
		input  wire        HPS_h2f_lw_axi_master_wlast,                                       //                                                            .wlast
		input  wire        HPS_h2f_lw_axi_master_wvalid,                                      //                                                            .wvalid
		output wire        HPS_h2f_lw_axi_master_wready,                                      //                                                            .wready
		output wire [11:0] HPS_h2f_lw_axi_master_bid,                                         //                                                            .bid
		output wire [1:0]  HPS_h2f_lw_axi_master_bresp,                                       //                                                            .bresp
		output wire        HPS_h2f_lw_axi_master_bvalid,                                      //                                                            .bvalid
		input  wire        HPS_h2f_lw_axi_master_bready,                                      //                                                            .bready
		input  wire [11:0] HPS_h2f_lw_axi_master_arid,                                        //                                                            .arid
		input  wire [20:0] HPS_h2f_lw_axi_master_araddr,                                      //                                                            .araddr
		input  wire [3:0]  HPS_h2f_lw_axi_master_arlen,                                       //                                                            .arlen
		input  wire [2:0]  HPS_h2f_lw_axi_master_arsize,                                      //                                                            .arsize
		input  wire [1:0]  HPS_h2f_lw_axi_master_arburst,                                     //                                                            .arburst
		input  wire [1:0]  HPS_h2f_lw_axi_master_arlock,                                      //                                                            .arlock
		input  wire [3:0]  HPS_h2f_lw_axi_master_arcache,                                     //                                                            .arcache
		input  wire [2:0]  HPS_h2f_lw_axi_master_arprot,                                      //                                                            .arprot
		input  wire        HPS_h2f_lw_axi_master_arvalid,                                     //                                                            .arvalid
		output wire        HPS_h2f_lw_axi_master_arready,                                     //                                                            .arready
		output wire [11:0] HPS_h2f_lw_axi_master_rid,                                         //                                                            .rid
		output wire [31:0] HPS_h2f_lw_axi_master_rdata,                                       //                                                            .rdata
		output wire [1:0]  HPS_h2f_lw_axi_master_rresp,                                       //                                                            .rresp
		output wire        HPS_h2f_lw_axi_master_rlast,                                       //                                                            .rlast
		output wire        HPS_h2f_lw_axi_master_rvalid,                                      //                                                            .rvalid
		input  wire        HPS_h2f_lw_axi_master_rready,                                      //                                                            .rready
		input  wire        CLK_clk_clk,                                                       //                                                     CLK_clk.clk
		input  wire        AudioRAM_reset1_reset_bridge_in_reset_reset,                       //                       AudioRAM_reset1_reset_bridge_in_reset.reset
		input  wire        HPS_h2f_lw_axi_master_agent_clk_reset_reset_bridge_in_reset_reset, // HPS_h2f_lw_axi_master_agent_clk_reset_reset_bridge_in_reset.reset
		output wire [14:0] AudioRAM_s2_address,                                               //                                                 AudioRAM_s2.address
		output wire        AudioRAM_s2_write,                                                 //                                                            .write
		input  wire [7:0]  AudioRAM_s2_readdata,                                              //                                                            .readdata
		output wire [7:0]  AudioRAM_s2_writedata,                                             //                                                            .writedata
		output wire        AudioRAM_s2_chipselect,                                            //                                                            .chipselect
		output wire        AudioRAM_s2_clken                                                  //                                                            .clken
	);

	wire          rsp_mux_src_valid;                                  // rsp_mux:src_valid -> HPS_h2f_lw_axi_master_agent:write_rp_valid
	wire  [111:0] rsp_mux_src_data;                                   // rsp_mux:src_data -> HPS_h2f_lw_axi_master_agent:write_rp_data
	wire          rsp_mux_src_ready;                                  // HPS_h2f_lw_axi_master_agent:write_rp_ready -> rsp_mux:src_ready
	wire    [1:0] rsp_mux_src_channel;                                // rsp_mux:src_channel -> HPS_h2f_lw_axi_master_agent:write_rp_channel
	wire          rsp_mux_src_startofpacket;                          // rsp_mux:src_startofpacket -> HPS_h2f_lw_axi_master_agent:write_rp_startofpacket
	wire          rsp_mux_src_endofpacket;                            // rsp_mux:src_endofpacket -> HPS_h2f_lw_axi_master_agent:write_rp_endofpacket
	wire          rsp_mux_001_src_valid;                              // rsp_mux_001:src_valid -> HPS_h2f_lw_axi_master_agent:read_rp_valid
	wire  [111:0] rsp_mux_001_src_data;                               // rsp_mux_001:src_data -> HPS_h2f_lw_axi_master_agent:read_rp_data
	wire          rsp_mux_001_src_ready;                              // HPS_h2f_lw_axi_master_agent:read_rp_ready -> rsp_mux_001:src_ready
	wire    [1:0] rsp_mux_001_src_channel;                            // rsp_mux_001:src_channel -> HPS_h2f_lw_axi_master_agent:read_rp_channel
	wire          rsp_mux_001_src_startofpacket;                      // rsp_mux_001:src_startofpacket -> HPS_h2f_lw_axi_master_agent:read_rp_startofpacket
	wire          rsp_mux_001_src_endofpacket;                        // rsp_mux_001:src_endofpacket -> HPS_h2f_lw_axi_master_agent:read_rp_endofpacket
	wire    [7:0] audioram_s2_agent_m0_readdata;                      // AudioRAM_s2_translator:uav_readdata -> AudioRAM_s2_agent:m0_readdata
	wire          audioram_s2_agent_m0_waitrequest;                   // AudioRAM_s2_translator:uav_waitrequest -> AudioRAM_s2_agent:m0_waitrequest
	wire          audioram_s2_agent_m0_debugaccess;                   // AudioRAM_s2_agent:m0_debugaccess -> AudioRAM_s2_translator:uav_debugaccess
	wire   [20:0] audioram_s2_agent_m0_address;                       // AudioRAM_s2_agent:m0_address -> AudioRAM_s2_translator:uav_address
	wire    [0:0] audioram_s2_agent_m0_byteenable;                    // AudioRAM_s2_agent:m0_byteenable -> AudioRAM_s2_translator:uav_byteenable
	wire          audioram_s2_agent_m0_read;                          // AudioRAM_s2_agent:m0_read -> AudioRAM_s2_translator:uav_read
	wire          audioram_s2_agent_m0_readdatavalid;                 // AudioRAM_s2_translator:uav_readdatavalid -> AudioRAM_s2_agent:m0_readdatavalid
	wire          audioram_s2_agent_m0_lock;                          // AudioRAM_s2_agent:m0_lock -> AudioRAM_s2_translator:uav_lock
	wire    [7:0] audioram_s2_agent_m0_writedata;                     // AudioRAM_s2_agent:m0_writedata -> AudioRAM_s2_translator:uav_writedata
	wire          audioram_s2_agent_m0_write;                         // AudioRAM_s2_agent:m0_write -> AudioRAM_s2_translator:uav_write
	wire    [0:0] audioram_s2_agent_m0_burstcount;                    // AudioRAM_s2_agent:m0_burstcount -> AudioRAM_s2_translator:uav_burstcount
	wire          audioram_s2_agent_rf_source_valid;                  // AudioRAM_s2_agent:rf_source_valid -> AudioRAM_s2_agent_rsp_fifo:in_valid
	wire   [85:0] audioram_s2_agent_rf_source_data;                   // AudioRAM_s2_agent:rf_source_data -> AudioRAM_s2_agent_rsp_fifo:in_data
	wire          audioram_s2_agent_rf_source_ready;                  // AudioRAM_s2_agent_rsp_fifo:in_ready -> AudioRAM_s2_agent:rf_source_ready
	wire          audioram_s2_agent_rf_source_startofpacket;          // AudioRAM_s2_agent:rf_source_startofpacket -> AudioRAM_s2_agent_rsp_fifo:in_startofpacket
	wire          audioram_s2_agent_rf_source_endofpacket;            // AudioRAM_s2_agent:rf_source_endofpacket -> AudioRAM_s2_agent_rsp_fifo:in_endofpacket
	wire          audioram_s2_agent_rsp_fifo_out_valid;               // AudioRAM_s2_agent_rsp_fifo:out_valid -> AudioRAM_s2_agent:rf_sink_valid
	wire   [85:0] audioram_s2_agent_rsp_fifo_out_data;                // AudioRAM_s2_agent_rsp_fifo:out_data -> AudioRAM_s2_agent:rf_sink_data
	wire          audioram_s2_agent_rsp_fifo_out_ready;               // AudioRAM_s2_agent:rf_sink_ready -> AudioRAM_s2_agent_rsp_fifo:out_ready
	wire          audioram_s2_agent_rsp_fifo_out_startofpacket;       // AudioRAM_s2_agent_rsp_fifo:out_startofpacket -> AudioRAM_s2_agent:rf_sink_startofpacket
	wire          audioram_s2_agent_rsp_fifo_out_endofpacket;         // AudioRAM_s2_agent_rsp_fifo:out_endofpacket -> AudioRAM_s2_agent:rf_sink_endofpacket
	wire          audioram_s2_agent_rdata_fifo_src_valid;             // AudioRAM_s2_agent:rdata_fifo_src_valid -> AudioRAM_s2_agent_rdata_fifo:in_valid
	wire    [9:0] audioram_s2_agent_rdata_fifo_src_data;              // AudioRAM_s2_agent:rdata_fifo_src_data -> AudioRAM_s2_agent_rdata_fifo:in_data
	wire          audioram_s2_agent_rdata_fifo_src_ready;             // AudioRAM_s2_agent_rdata_fifo:in_ready -> AudioRAM_s2_agent:rdata_fifo_src_ready
	wire          hps_h2f_lw_axi_master_agent_write_cp_valid;         // HPS_h2f_lw_axi_master_agent:write_cp_valid -> router:sink_valid
	wire  [111:0] hps_h2f_lw_axi_master_agent_write_cp_data;          // HPS_h2f_lw_axi_master_agent:write_cp_data -> router:sink_data
	wire          hps_h2f_lw_axi_master_agent_write_cp_ready;         // router:sink_ready -> HPS_h2f_lw_axi_master_agent:write_cp_ready
	wire          hps_h2f_lw_axi_master_agent_write_cp_startofpacket; // HPS_h2f_lw_axi_master_agent:write_cp_startofpacket -> router:sink_startofpacket
	wire          hps_h2f_lw_axi_master_agent_write_cp_endofpacket;   // HPS_h2f_lw_axi_master_agent:write_cp_endofpacket -> router:sink_endofpacket
	wire          router_src_valid;                                   // router:src_valid -> cmd_demux:sink_valid
	wire  [111:0] router_src_data;                                    // router:src_data -> cmd_demux:sink_data
	wire          router_src_ready;                                   // cmd_demux:sink_ready -> router:src_ready
	wire    [1:0] router_src_channel;                                 // router:src_channel -> cmd_demux:sink_channel
	wire          router_src_startofpacket;                           // router:src_startofpacket -> cmd_demux:sink_startofpacket
	wire          router_src_endofpacket;                             // router:src_endofpacket -> cmd_demux:sink_endofpacket
	wire          hps_h2f_lw_axi_master_agent_read_cp_valid;          // HPS_h2f_lw_axi_master_agent:read_cp_valid -> router_001:sink_valid
	wire  [111:0] hps_h2f_lw_axi_master_agent_read_cp_data;           // HPS_h2f_lw_axi_master_agent:read_cp_data -> router_001:sink_data
	wire          hps_h2f_lw_axi_master_agent_read_cp_ready;          // router_001:sink_ready -> HPS_h2f_lw_axi_master_agent:read_cp_ready
	wire          hps_h2f_lw_axi_master_agent_read_cp_startofpacket;  // HPS_h2f_lw_axi_master_agent:read_cp_startofpacket -> router_001:sink_startofpacket
	wire          hps_h2f_lw_axi_master_agent_read_cp_endofpacket;    // HPS_h2f_lw_axi_master_agent:read_cp_endofpacket -> router_001:sink_endofpacket
	wire          router_001_src_valid;                               // router_001:src_valid -> cmd_demux_001:sink_valid
	wire  [111:0] router_001_src_data;                                // router_001:src_data -> cmd_demux_001:sink_data
	wire          router_001_src_ready;                               // cmd_demux_001:sink_ready -> router_001:src_ready
	wire    [1:0] router_001_src_channel;                             // router_001:src_channel -> cmd_demux_001:sink_channel
	wire          router_001_src_startofpacket;                       // router_001:src_startofpacket -> cmd_demux_001:sink_startofpacket
	wire          router_001_src_endofpacket;                         // router_001:src_endofpacket -> cmd_demux_001:sink_endofpacket
	wire          audioram_s2_agent_rp_valid;                         // AudioRAM_s2_agent:rp_valid -> router_002:sink_valid
	wire   [84:0] audioram_s2_agent_rp_data;                          // AudioRAM_s2_agent:rp_data -> router_002:sink_data
	wire          audioram_s2_agent_rp_ready;                         // router_002:sink_ready -> AudioRAM_s2_agent:rp_ready
	wire          audioram_s2_agent_rp_startofpacket;                 // AudioRAM_s2_agent:rp_startofpacket -> router_002:sink_startofpacket
	wire          audioram_s2_agent_rp_endofpacket;                   // AudioRAM_s2_agent:rp_endofpacket -> router_002:sink_endofpacket
	wire          audioram_s2_burst_adapter_source0_valid;            // AudioRAM_s2_burst_adapter:source0_valid -> AudioRAM_s2_agent:cp_valid
	wire   [84:0] audioram_s2_burst_adapter_source0_data;             // AudioRAM_s2_burst_adapter:source0_data -> AudioRAM_s2_agent:cp_data
	wire          audioram_s2_burst_adapter_source0_ready;            // AudioRAM_s2_agent:cp_ready -> AudioRAM_s2_burst_adapter:source0_ready
	wire    [1:0] audioram_s2_burst_adapter_source0_channel;          // AudioRAM_s2_burst_adapter:source0_channel -> AudioRAM_s2_agent:cp_channel
	wire          audioram_s2_burst_adapter_source0_startofpacket;    // AudioRAM_s2_burst_adapter:source0_startofpacket -> AudioRAM_s2_agent:cp_startofpacket
	wire          audioram_s2_burst_adapter_source0_endofpacket;      // AudioRAM_s2_burst_adapter:source0_endofpacket -> AudioRAM_s2_agent:cp_endofpacket
	wire          cmd_demux_src0_valid;                               // cmd_demux:src0_valid -> cmd_mux:sink0_valid
	wire  [111:0] cmd_demux_src0_data;                                // cmd_demux:src0_data -> cmd_mux:sink0_data
	wire          cmd_demux_src0_ready;                               // cmd_mux:sink0_ready -> cmd_demux:src0_ready
	wire    [1:0] cmd_demux_src0_channel;                             // cmd_demux:src0_channel -> cmd_mux:sink0_channel
	wire          cmd_demux_src0_startofpacket;                       // cmd_demux:src0_startofpacket -> cmd_mux:sink0_startofpacket
	wire          cmd_demux_src0_endofpacket;                         // cmd_demux:src0_endofpacket -> cmd_mux:sink0_endofpacket
	wire          cmd_demux_001_src0_valid;                           // cmd_demux_001:src0_valid -> cmd_mux:sink1_valid
	wire  [111:0] cmd_demux_001_src0_data;                            // cmd_demux_001:src0_data -> cmd_mux:sink1_data
	wire          cmd_demux_001_src0_ready;                           // cmd_mux:sink1_ready -> cmd_demux_001:src0_ready
	wire    [1:0] cmd_demux_001_src0_channel;                         // cmd_demux_001:src0_channel -> cmd_mux:sink1_channel
	wire          cmd_demux_001_src0_startofpacket;                   // cmd_demux_001:src0_startofpacket -> cmd_mux:sink1_startofpacket
	wire          cmd_demux_001_src0_endofpacket;                     // cmd_demux_001:src0_endofpacket -> cmd_mux:sink1_endofpacket
	wire          rsp_demux_src0_valid;                               // rsp_demux:src0_valid -> rsp_mux:sink0_valid
	wire  [111:0] rsp_demux_src0_data;                                // rsp_demux:src0_data -> rsp_mux:sink0_data
	wire          rsp_demux_src0_ready;                               // rsp_mux:sink0_ready -> rsp_demux:src0_ready
	wire    [1:0] rsp_demux_src0_channel;                             // rsp_demux:src0_channel -> rsp_mux:sink0_channel
	wire          rsp_demux_src0_startofpacket;                       // rsp_demux:src0_startofpacket -> rsp_mux:sink0_startofpacket
	wire          rsp_demux_src0_endofpacket;                         // rsp_demux:src0_endofpacket -> rsp_mux:sink0_endofpacket
	wire          rsp_demux_src1_valid;                               // rsp_demux:src1_valid -> rsp_mux_001:sink0_valid
	wire  [111:0] rsp_demux_src1_data;                                // rsp_demux:src1_data -> rsp_mux_001:sink0_data
	wire          rsp_demux_src1_ready;                               // rsp_mux_001:sink0_ready -> rsp_demux:src1_ready
	wire    [1:0] rsp_demux_src1_channel;                             // rsp_demux:src1_channel -> rsp_mux_001:sink0_channel
	wire          rsp_demux_src1_startofpacket;                       // rsp_demux:src1_startofpacket -> rsp_mux_001:sink0_startofpacket
	wire          rsp_demux_src1_endofpacket;                         // rsp_demux:src1_endofpacket -> rsp_mux_001:sink0_endofpacket
	wire          router_002_src_valid;                               // router_002:src_valid -> AudioRAM_s2_rsp_width_adapter:in_valid
	wire   [84:0] router_002_src_data;                                // router_002:src_data -> AudioRAM_s2_rsp_width_adapter:in_data
	wire          router_002_src_ready;                               // AudioRAM_s2_rsp_width_adapter:in_ready -> router_002:src_ready
	wire    [1:0] router_002_src_channel;                             // router_002:src_channel -> AudioRAM_s2_rsp_width_adapter:in_channel
	wire          router_002_src_startofpacket;                       // router_002:src_startofpacket -> AudioRAM_s2_rsp_width_adapter:in_startofpacket
	wire          router_002_src_endofpacket;                         // router_002:src_endofpacket -> AudioRAM_s2_rsp_width_adapter:in_endofpacket
	wire          audioram_s2_rsp_width_adapter_src_valid;            // AudioRAM_s2_rsp_width_adapter:out_valid -> rsp_demux:sink_valid
	wire  [111:0] audioram_s2_rsp_width_adapter_src_data;             // AudioRAM_s2_rsp_width_adapter:out_data -> rsp_demux:sink_data
	wire          audioram_s2_rsp_width_adapter_src_ready;            // rsp_demux:sink_ready -> AudioRAM_s2_rsp_width_adapter:out_ready
	wire    [1:0] audioram_s2_rsp_width_adapter_src_channel;          // AudioRAM_s2_rsp_width_adapter:out_channel -> rsp_demux:sink_channel
	wire          audioram_s2_rsp_width_adapter_src_startofpacket;    // AudioRAM_s2_rsp_width_adapter:out_startofpacket -> rsp_demux:sink_startofpacket
	wire          audioram_s2_rsp_width_adapter_src_endofpacket;      // AudioRAM_s2_rsp_width_adapter:out_endofpacket -> rsp_demux:sink_endofpacket
	wire          cmd_mux_src_valid;                                  // cmd_mux:src_valid -> AudioRAM_s2_cmd_width_adapter:in_valid
	wire  [111:0] cmd_mux_src_data;                                   // cmd_mux:src_data -> AudioRAM_s2_cmd_width_adapter:in_data
	wire          cmd_mux_src_ready;                                  // AudioRAM_s2_cmd_width_adapter:in_ready -> cmd_mux:src_ready
	wire    [1:0] cmd_mux_src_channel;                                // cmd_mux:src_channel -> AudioRAM_s2_cmd_width_adapter:in_channel
	wire          cmd_mux_src_startofpacket;                          // cmd_mux:src_startofpacket -> AudioRAM_s2_cmd_width_adapter:in_startofpacket
	wire          cmd_mux_src_endofpacket;                            // cmd_mux:src_endofpacket -> AudioRAM_s2_cmd_width_adapter:in_endofpacket
	wire          audioram_s2_cmd_width_adapter_src_valid;            // AudioRAM_s2_cmd_width_adapter:out_valid -> AudioRAM_s2_burst_adapter:sink0_valid
	wire   [84:0] audioram_s2_cmd_width_adapter_src_data;             // AudioRAM_s2_cmd_width_adapter:out_data -> AudioRAM_s2_burst_adapter:sink0_data
	wire          audioram_s2_cmd_width_adapter_src_ready;            // AudioRAM_s2_burst_adapter:sink0_ready -> AudioRAM_s2_cmd_width_adapter:out_ready
	wire    [1:0] audioram_s2_cmd_width_adapter_src_channel;          // AudioRAM_s2_cmd_width_adapter:out_channel -> AudioRAM_s2_burst_adapter:sink0_channel
	wire          audioram_s2_cmd_width_adapter_src_startofpacket;    // AudioRAM_s2_cmd_width_adapter:out_startofpacket -> AudioRAM_s2_burst_adapter:sink0_startofpacket
	wire          audioram_s2_cmd_width_adapter_src_endofpacket;      // AudioRAM_s2_cmd_width_adapter:out_endofpacket -> AudioRAM_s2_burst_adapter:sink0_endofpacket
	wire          audioram_s2_agent_rdata_fifo_out_valid;             // AudioRAM_s2_agent_rdata_fifo:out_valid -> avalon_st_adapter:in_0_valid
	wire    [9:0] audioram_s2_agent_rdata_fifo_out_data;              // AudioRAM_s2_agent_rdata_fifo:out_data -> avalon_st_adapter:in_0_data
	wire          audioram_s2_agent_rdata_fifo_out_ready;             // avalon_st_adapter:in_0_ready -> AudioRAM_s2_agent_rdata_fifo:out_ready
	wire          avalon_st_adapter_out_0_valid;                      // avalon_st_adapter:out_0_valid -> AudioRAM_s2_agent:rdata_fifo_sink_valid
	wire    [9:0] avalon_st_adapter_out_0_data;                       // avalon_st_adapter:out_0_data -> AudioRAM_s2_agent:rdata_fifo_sink_data
	wire          avalon_st_adapter_out_0_ready;                      // AudioRAM_s2_agent:rdata_fifo_sink_ready -> avalon_st_adapter:out_0_ready
	wire    [0:0] avalon_st_adapter_out_0_error;                      // avalon_st_adapter:out_0_error -> AudioRAM_s2_agent:rdata_fifo_sink_error

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (15),
		.AV_DATA_W                      (8),
		.UAV_DATA_W                     (8),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (1),
		.UAV_BYTEENABLE_W               (1),
		.UAV_ADDRESS_W                  (21),
		.UAV_BURSTCOUNT_W               (1),
		.AV_READLATENCY                 (1),
		.USE_READDATAVALID              (0),
		.USE_WAITREQUEST                (0),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (1),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (0),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) audioram_s2_translator (
		.clk                    (CLK_clk_clk),                                 //                      clk.clk
		.reset                  (AudioRAM_reset1_reset_bridge_in_reset_reset), //                    reset.reset
		.uav_address            (audioram_s2_agent_m0_address),                // avalon_universal_slave_0.address
		.uav_burstcount         (audioram_s2_agent_m0_burstcount),             //                         .burstcount
		.uav_read               (audioram_s2_agent_m0_read),                   //                         .read
		.uav_write              (audioram_s2_agent_m0_write),                  //                         .write
		.uav_waitrequest        (audioram_s2_agent_m0_waitrequest),            //                         .waitrequest
		.uav_readdatavalid      (audioram_s2_agent_m0_readdatavalid),          //                         .readdatavalid
		.uav_byteenable         (audioram_s2_agent_m0_byteenable),             //                         .byteenable
		.uav_readdata           (audioram_s2_agent_m0_readdata),               //                         .readdata
		.uav_writedata          (audioram_s2_agent_m0_writedata),              //                         .writedata
		.uav_lock               (audioram_s2_agent_m0_lock),                   //                         .lock
		.uav_debugaccess        (audioram_s2_agent_m0_debugaccess),            //                         .debugaccess
		.av_address             (AudioRAM_s2_address),                         //      avalon_anti_slave_0.address
		.av_write               (AudioRAM_s2_write),                           //                         .write
		.av_readdata            (AudioRAM_s2_readdata),                        //                         .readdata
		.av_writedata           (AudioRAM_s2_writedata),                       //                         .writedata
		.av_chipselect          (AudioRAM_s2_chipselect),                      //                         .chipselect
		.av_clken               (AudioRAM_s2_clken),                           //                         .clken
		.av_read                (),                                            //              (terminated)
		.av_begintransfer       (),                                            //              (terminated)
		.av_beginbursttransfer  (),                                            //              (terminated)
		.av_burstcount          (),                                            //              (terminated)
		.av_byteenable          (),                                            //              (terminated)
		.av_readdatavalid       (1'b0),                                        //              (terminated)
		.av_waitrequest         (1'b0),                                        //              (terminated)
		.av_writebyteenable     (),                                            //              (terminated)
		.av_lock                (),                                            //              (terminated)
		.uav_clken              (1'b0),                                        //              (terminated)
		.av_debugaccess         (),                                            //              (terminated)
		.av_outputenable        (),                                            //              (terminated)
		.uav_response           (),                                            //              (terminated)
		.av_response            (2'b00),                                       //              (terminated)
		.uav_writeresponsevalid (),                                            //              (terminated)
		.av_writeresponsevalid  (1'b0)                                         //              (terminated)
	);

	altera_merlin_axi_master_ni #(
		.ID_WIDTH                  (12),
		.ADDR_WIDTH                (21),
		.RDATA_WIDTH               (32),
		.WDATA_WIDTH               (32),
		.ADDR_USER_WIDTH           (1),
		.DATA_USER_WIDTH           (1),
		.AXI_BURST_LENGTH_WIDTH    (4),
		.AXI_LOCK_WIDTH            (2),
		.AXI_VERSION               ("AXI3"),
		.WRITE_ISSUING_CAPABILITY  (8),
		.READ_ISSUING_CAPABILITY   (8),
		.PKT_BEGIN_BURST           (84),
		.PKT_CACHE_H               (106),
		.PKT_CACHE_L               (103),
		.PKT_ADDR_SIDEBAND_H       (82),
		.PKT_ADDR_SIDEBAND_L       (82),
		.PKT_PROTECTION_H          (102),
		.PKT_PROTECTION_L          (100),
		.PKT_BURST_SIZE_H          (79),
		.PKT_BURST_SIZE_L          (77),
		.PKT_BURST_TYPE_H          (81),
		.PKT_BURST_TYPE_L          (80),
		.PKT_RESPONSE_STATUS_L     (107),
		.PKT_RESPONSE_STATUS_H     (108),
		.PKT_BURSTWRAP_H           (76),
		.PKT_BURSTWRAP_L           (70),
		.PKT_BYTE_CNT_H            (69),
		.PKT_BYTE_CNT_L            (63),
		.PKT_ADDR_H                (56),
		.PKT_ADDR_L                (36),
		.PKT_TRANS_EXCLUSIVE       (62),
		.PKT_TRANS_LOCK            (61),
		.PKT_TRANS_COMPRESSED_READ (57),
		.PKT_TRANS_POSTED          (58),
		.PKT_TRANS_WRITE           (59),
		.PKT_TRANS_READ            (60),
		.PKT_DATA_H                (31),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (35),
		.PKT_BYTEEN_L              (32),
		.PKT_SRC_ID_H              (86),
		.PKT_SRC_ID_L              (86),
		.PKT_DEST_ID_H             (87),
		.PKT_DEST_ID_L             (87),
		.PKT_THREAD_ID_H           (99),
		.PKT_THREAD_ID_L           (88),
		.PKT_QOS_L                 (85),
		.PKT_QOS_H                 (85),
		.PKT_ORI_BURST_SIZE_L      (109),
		.PKT_ORI_BURST_SIZE_H      (111),
		.PKT_DATA_SIDEBAND_H       (83),
		.PKT_DATA_SIDEBAND_L       (83),
		.ST_DATA_W                 (112),
		.ST_CHANNEL_W              (2),
		.ID                        (0)
	) hps_h2f_lw_axi_master_agent (
		.aclk                   (CLK_clk_clk),                                                        //              clk.clk
		.aresetn                (~HPS_h2f_lw_axi_master_agent_clk_reset_reset_bridge_in_reset_reset), //        clk_reset.reset_n
		.write_cp_valid         (hps_h2f_lw_axi_master_agent_write_cp_valid),                         //         write_cp.valid
		.write_cp_data          (hps_h2f_lw_axi_master_agent_write_cp_data),                          //                 .data
		.write_cp_startofpacket (hps_h2f_lw_axi_master_agent_write_cp_startofpacket),                 //                 .startofpacket
		.write_cp_endofpacket   (hps_h2f_lw_axi_master_agent_write_cp_endofpacket),                   //                 .endofpacket
		.write_cp_ready         (hps_h2f_lw_axi_master_agent_write_cp_ready),                         //                 .ready
		.write_rp_valid         (rsp_mux_src_valid),                                                  //         write_rp.valid
		.write_rp_data          (rsp_mux_src_data),                                                   //                 .data
		.write_rp_channel       (rsp_mux_src_channel),                                                //                 .channel
		.write_rp_startofpacket (rsp_mux_src_startofpacket),                                          //                 .startofpacket
		.write_rp_endofpacket   (rsp_mux_src_endofpacket),                                            //                 .endofpacket
		.write_rp_ready         (rsp_mux_src_ready),                                                  //                 .ready
		.read_cp_valid          (hps_h2f_lw_axi_master_agent_read_cp_valid),                          //          read_cp.valid
		.read_cp_data           (hps_h2f_lw_axi_master_agent_read_cp_data),                           //                 .data
		.read_cp_startofpacket  (hps_h2f_lw_axi_master_agent_read_cp_startofpacket),                  //                 .startofpacket
		.read_cp_endofpacket    (hps_h2f_lw_axi_master_agent_read_cp_endofpacket),                    //                 .endofpacket
		.read_cp_ready          (hps_h2f_lw_axi_master_agent_read_cp_ready),                          //                 .ready
		.read_rp_valid          (rsp_mux_001_src_valid),                                              //          read_rp.valid
		.read_rp_data           (rsp_mux_001_src_data),                                               //                 .data
		.read_rp_channel        (rsp_mux_001_src_channel),                                            //                 .channel
		.read_rp_startofpacket  (rsp_mux_001_src_startofpacket),                                      //                 .startofpacket
		.read_rp_endofpacket    (rsp_mux_001_src_endofpacket),                                        //                 .endofpacket
		.read_rp_ready          (rsp_mux_001_src_ready),                                              //                 .ready
		.awid                   (HPS_h2f_lw_axi_master_awid),                                         // altera_axi_slave.awid
		.awaddr                 (HPS_h2f_lw_axi_master_awaddr),                                       //                 .awaddr
		.awlen                  (HPS_h2f_lw_axi_master_awlen),                                        //                 .awlen
		.awsize                 (HPS_h2f_lw_axi_master_awsize),                                       //                 .awsize
		.awburst                (HPS_h2f_lw_axi_master_awburst),                                      //                 .awburst
		.awlock                 (HPS_h2f_lw_axi_master_awlock),                                       //                 .awlock
		.awcache                (HPS_h2f_lw_axi_master_awcache),                                      //                 .awcache
		.awprot                 (HPS_h2f_lw_axi_master_awprot),                                       //                 .awprot
		.awvalid                (HPS_h2f_lw_axi_master_awvalid),                                      //                 .awvalid
		.awready                (HPS_h2f_lw_axi_master_awready),                                      //                 .awready
		.wid                    (HPS_h2f_lw_axi_master_wid),                                          //                 .wid
		.wdata                  (HPS_h2f_lw_axi_master_wdata),                                        //                 .wdata
		.wstrb                  (HPS_h2f_lw_axi_master_wstrb),                                        //                 .wstrb
		.wlast                  (HPS_h2f_lw_axi_master_wlast),                                        //                 .wlast
		.wvalid                 (HPS_h2f_lw_axi_master_wvalid),                                       //                 .wvalid
		.wready                 (HPS_h2f_lw_axi_master_wready),                                       //                 .wready
		.bid                    (HPS_h2f_lw_axi_master_bid),                                          //                 .bid
		.bresp                  (HPS_h2f_lw_axi_master_bresp),                                        //                 .bresp
		.bvalid                 (HPS_h2f_lw_axi_master_bvalid),                                       //                 .bvalid
		.bready                 (HPS_h2f_lw_axi_master_bready),                                       //                 .bready
		.arid                   (HPS_h2f_lw_axi_master_arid),                                         //                 .arid
		.araddr                 (HPS_h2f_lw_axi_master_araddr),                                       //                 .araddr
		.arlen                  (HPS_h2f_lw_axi_master_arlen),                                        //                 .arlen
		.arsize                 (HPS_h2f_lw_axi_master_arsize),                                       //                 .arsize
		.arburst                (HPS_h2f_lw_axi_master_arburst),                                      //                 .arburst
		.arlock                 (HPS_h2f_lw_axi_master_arlock),                                       //                 .arlock
		.arcache                (HPS_h2f_lw_axi_master_arcache),                                      //                 .arcache
		.arprot                 (HPS_h2f_lw_axi_master_arprot),                                       //                 .arprot
		.arvalid                (HPS_h2f_lw_axi_master_arvalid),                                      //                 .arvalid
		.arready                (HPS_h2f_lw_axi_master_arready),                                      //                 .arready
		.rid                    (HPS_h2f_lw_axi_master_rid),                                          //                 .rid
		.rdata                  (HPS_h2f_lw_axi_master_rdata),                                        //                 .rdata
		.rresp                  (HPS_h2f_lw_axi_master_rresp),                                        //                 .rresp
		.rlast                  (HPS_h2f_lw_axi_master_rlast),                                        //                 .rlast
		.rvalid                 (HPS_h2f_lw_axi_master_rvalid),                                       //                 .rvalid
		.rready                 (HPS_h2f_lw_axi_master_rready),                                       //                 .rready
		.awuser                 (1'b0),                                                               //      (terminated)
		.aruser                 (1'b0),                                                               //      (terminated)
		.awqos                  (4'b0000),                                                            //      (terminated)
		.arqos                  (4'b0000),                                                            //      (terminated)
		.awregion               (4'b0000),                                                            //      (terminated)
		.arregion               (4'b0000),                                                            //      (terminated)
		.wuser                  (1'b0),                                                               //      (terminated)
		.ruser                  (),                                                                   //      (terminated)
		.buser                  ()                                                                    //      (terminated)
	);

	altera_merlin_slave_agent #(
		.PKT_ORI_BURST_SIZE_H      (84),
		.PKT_ORI_BURST_SIZE_L      (82),
		.PKT_RESPONSE_STATUS_H     (81),
		.PKT_RESPONSE_STATUS_L     (80),
		.PKT_BURST_SIZE_H          (52),
		.PKT_BURST_SIZE_L          (50),
		.PKT_TRANS_LOCK            (34),
		.PKT_BEGIN_BURST           (57),
		.PKT_PROTECTION_H          (75),
		.PKT_PROTECTION_L          (73),
		.PKT_BURSTWRAP_H           (49),
		.PKT_BURSTWRAP_L           (43),
		.PKT_BYTE_CNT_H            (42),
		.PKT_BYTE_CNT_L            (36),
		.PKT_ADDR_H                (29),
		.PKT_ADDR_L                (9),
		.PKT_TRANS_COMPRESSED_READ (30),
		.PKT_TRANS_POSTED          (31),
		.PKT_TRANS_WRITE           (32),
		.PKT_TRANS_READ            (33),
		.PKT_DATA_H                (7),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (8),
		.PKT_BYTEEN_L              (8),
		.PKT_SRC_ID_H              (59),
		.PKT_SRC_ID_L              (59),
		.PKT_DEST_ID_H             (60),
		.PKT_DEST_ID_L             (60),
		.PKT_SYMBOL_W              (8),
		.ST_CHANNEL_W              (2),
		.ST_DATA_W                 (85),
		.AVS_BURSTCOUNT_W          (1),
		.SUPPRESS_0_BYTEEN_CMD     (1),
		.PREVENT_FIFO_OVERFLOW     (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0),
		.ECC_ENABLE                (0)
	) audioram_s2_agent (
		.clk                     (CLK_clk_clk),                                     //             clk.clk
		.reset                   (AudioRAM_reset1_reset_bridge_in_reset_reset),     //       clk_reset.reset
		.m0_address              (audioram_s2_agent_m0_address),                    //              m0.address
		.m0_burstcount           (audioram_s2_agent_m0_burstcount),                 //                .burstcount
		.m0_byteenable           (audioram_s2_agent_m0_byteenable),                 //                .byteenable
		.m0_debugaccess          (audioram_s2_agent_m0_debugaccess),                //                .debugaccess
		.m0_lock                 (audioram_s2_agent_m0_lock),                       //                .lock
		.m0_readdata             (audioram_s2_agent_m0_readdata),                   //                .readdata
		.m0_readdatavalid        (audioram_s2_agent_m0_readdatavalid),              //                .readdatavalid
		.m0_read                 (audioram_s2_agent_m0_read),                       //                .read
		.m0_waitrequest          (audioram_s2_agent_m0_waitrequest),                //                .waitrequest
		.m0_writedata            (audioram_s2_agent_m0_writedata),                  //                .writedata
		.m0_write                (audioram_s2_agent_m0_write),                      //                .write
		.rp_endofpacket          (audioram_s2_agent_rp_endofpacket),                //              rp.endofpacket
		.rp_ready                (audioram_s2_agent_rp_ready),                      //                .ready
		.rp_valid                (audioram_s2_agent_rp_valid),                      //                .valid
		.rp_data                 (audioram_s2_agent_rp_data),                       //                .data
		.rp_startofpacket        (audioram_s2_agent_rp_startofpacket),              //                .startofpacket
		.cp_ready                (audioram_s2_burst_adapter_source0_ready),         //              cp.ready
		.cp_valid                (audioram_s2_burst_adapter_source0_valid),         //                .valid
		.cp_data                 (audioram_s2_burst_adapter_source0_data),          //                .data
		.cp_startofpacket        (audioram_s2_burst_adapter_source0_startofpacket), //                .startofpacket
		.cp_endofpacket          (audioram_s2_burst_adapter_source0_endofpacket),   //                .endofpacket
		.cp_channel              (audioram_s2_burst_adapter_source0_channel),       //                .channel
		.rf_sink_ready           (audioram_s2_agent_rsp_fifo_out_ready),            //         rf_sink.ready
		.rf_sink_valid           (audioram_s2_agent_rsp_fifo_out_valid),            //                .valid
		.rf_sink_startofpacket   (audioram_s2_agent_rsp_fifo_out_startofpacket),    //                .startofpacket
		.rf_sink_endofpacket     (audioram_s2_agent_rsp_fifo_out_endofpacket),      //                .endofpacket
		.rf_sink_data            (audioram_s2_agent_rsp_fifo_out_data),             //                .data
		.rf_source_ready         (audioram_s2_agent_rf_source_ready),               //       rf_source.ready
		.rf_source_valid         (audioram_s2_agent_rf_source_valid),               //                .valid
		.rf_source_startofpacket (audioram_s2_agent_rf_source_startofpacket),       //                .startofpacket
		.rf_source_endofpacket   (audioram_s2_agent_rf_source_endofpacket),         //                .endofpacket
		.rf_source_data          (audioram_s2_agent_rf_source_data),                //                .data
		.rdata_fifo_sink_ready   (avalon_st_adapter_out_0_ready),                   // rdata_fifo_sink.ready
		.rdata_fifo_sink_valid   (avalon_st_adapter_out_0_valid),                   //                .valid
		.rdata_fifo_sink_data    (avalon_st_adapter_out_0_data),                    //                .data
		.rdata_fifo_sink_error   (avalon_st_adapter_out_0_error),                   //                .error
		.rdata_fifo_src_ready    (audioram_s2_agent_rdata_fifo_src_ready),          //  rdata_fifo_src.ready
		.rdata_fifo_src_valid    (audioram_s2_agent_rdata_fifo_src_valid),          //                .valid
		.rdata_fifo_src_data     (audioram_s2_agent_rdata_fifo_src_data),           //                .data
		.m0_response             (2'b00),                                           //     (terminated)
		.m0_writeresponsevalid   (1'b0)                                             //     (terminated)
	);

	altera_avalon_sc_fifo #(
		.SYMBOLS_PER_BEAT    (1),
		.BITS_PER_SYMBOL     (86),
		.FIFO_DEPTH          (2),
		.CHANNEL_WIDTH       (0),
		.ERROR_WIDTH         (0),
		.USE_PACKETS         (1),
		.USE_FILL_LEVEL      (0),
		.EMPTY_LATENCY       (1),
		.USE_MEMORY_BLOCKS   (0),
		.USE_STORE_FORWARD   (0),
		.USE_ALMOST_FULL_IF  (0),
		.USE_ALMOST_EMPTY_IF (0)
	) audioram_s2_agent_rsp_fifo (
		.clk               (CLK_clk_clk),                                  //       clk.clk
		.reset             (AudioRAM_reset1_reset_bridge_in_reset_reset),  // clk_reset.reset
		.in_data           (audioram_s2_agent_rf_source_data),             //        in.data
		.in_valid          (audioram_s2_agent_rf_source_valid),            //          .valid
		.in_ready          (audioram_s2_agent_rf_source_ready),            //          .ready
		.in_startofpacket  (audioram_s2_agent_rf_source_startofpacket),    //          .startofpacket
		.in_endofpacket    (audioram_s2_agent_rf_source_endofpacket),      //          .endofpacket
		.out_data          (audioram_s2_agent_rsp_fifo_out_data),          //       out.data
		.out_valid         (audioram_s2_agent_rsp_fifo_out_valid),         //          .valid
		.out_ready         (audioram_s2_agent_rsp_fifo_out_ready),         //          .ready
		.out_startofpacket (audioram_s2_agent_rsp_fifo_out_startofpacket), //          .startofpacket
		.out_endofpacket   (audioram_s2_agent_rsp_fifo_out_endofpacket),   //          .endofpacket
		.csr_address       (2'b00),                                        // (terminated)
		.csr_read          (1'b0),                                         // (terminated)
		.csr_write         (1'b0),                                         // (terminated)
		.csr_readdata      (),                                             // (terminated)
		.csr_writedata     (32'b00000000000000000000000000000000),         // (terminated)
		.almost_full_data  (),                                             // (terminated)
		.almost_empty_data (),                                             // (terminated)
		.in_empty          (1'b0),                                         // (terminated)
		.out_empty         (),                                             // (terminated)
		.in_error          (1'b0),                                         // (terminated)
		.out_error         (),                                             // (terminated)
		.in_channel        (1'b0),                                         // (terminated)
		.out_channel       ()                                              // (terminated)
	);

	altera_avalon_sc_fifo #(
		.SYMBOLS_PER_BEAT    (1),
		.BITS_PER_SYMBOL     (10),
		.FIFO_DEPTH          (2),
		.CHANNEL_WIDTH       (0),
		.ERROR_WIDTH         (0),
		.USE_PACKETS         (0),
		.USE_FILL_LEVEL      (0),
		.EMPTY_LATENCY       (0),
		.USE_MEMORY_BLOCKS   (0),
		.USE_STORE_FORWARD   (0),
		.USE_ALMOST_FULL_IF  (0),
		.USE_ALMOST_EMPTY_IF (0)
	) audioram_s2_agent_rdata_fifo (
		.clk               (CLK_clk_clk),                                 //       clk.clk
		.reset             (AudioRAM_reset1_reset_bridge_in_reset_reset), // clk_reset.reset
		.in_data           (audioram_s2_agent_rdata_fifo_src_data),       //        in.data
		.in_valid          (audioram_s2_agent_rdata_fifo_src_valid),      //          .valid
		.in_ready          (audioram_s2_agent_rdata_fifo_src_ready),      //          .ready
		.out_data          (audioram_s2_agent_rdata_fifo_out_data),       //       out.data
		.out_valid         (audioram_s2_agent_rdata_fifo_out_valid),      //          .valid
		.out_ready         (audioram_s2_agent_rdata_fifo_out_ready),      //          .ready
		.csr_address       (2'b00),                                       // (terminated)
		.csr_read          (1'b0),                                        // (terminated)
		.csr_write         (1'b0),                                        // (terminated)
		.csr_readdata      (),                                            // (terminated)
		.csr_writedata     (32'b00000000000000000000000000000000),        // (terminated)
		.almost_full_data  (),                                            // (terminated)
		.almost_empty_data (),                                            // (terminated)
		.in_startofpacket  (1'b0),                                        // (terminated)
		.in_endofpacket    (1'b0),                                        // (terminated)
		.out_startofpacket (),                                            // (terminated)
		.out_endofpacket   (),                                            // (terminated)
		.in_empty          (1'b0),                                        // (terminated)
		.out_empty         (),                                            // (terminated)
		.in_error          (1'b0),                                        // (terminated)
		.out_error         (),                                            // (terminated)
		.in_channel        (1'b0),                                        // (terminated)
		.out_channel       ()                                             // (terminated)
	);

	MP3_PC_mm_interconnect_1_router router (
		.sink_ready         (hps_h2f_lw_axi_master_agent_write_cp_ready),                        //      sink.ready
		.sink_valid         (hps_h2f_lw_axi_master_agent_write_cp_valid),                        //          .valid
		.sink_data          (hps_h2f_lw_axi_master_agent_write_cp_data),                         //          .data
		.sink_startofpacket (hps_h2f_lw_axi_master_agent_write_cp_startofpacket),                //          .startofpacket
		.sink_endofpacket   (hps_h2f_lw_axi_master_agent_write_cp_endofpacket),                  //          .endofpacket
		.clk                (CLK_clk_clk),                                                       //       clk.clk
		.reset              (HPS_h2f_lw_axi_master_agent_clk_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready          (router_src_ready),                                                  //       src.ready
		.src_valid          (router_src_valid),                                                  //          .valid
		.src_data           (router_src_data),                                                   //          .data
		.src_channel        (router_src_channel),                                                //          .channel
		.src_startofpacket  (router_src_startofpacket),                                          //          .startofpacket
		.src_endofpacket    (router_src_endofpacket)                                             //          .endofpacket
	);

	MP3_PC_mm_interconnect_1_router router_001 (
		.sink_ready         (hps_h2f_lw_axi_master_agent_read_cp_ready),                         //      sink.ready
		.sink_valid         (hps_h2f_lw_axi_master_agent_read_cp_valid),                         //          .valid
		.sink_data          (hps_h2f_lw_axi_master_agent_read_cp_data),                          //          .data
		.sink_startofpacket (hps_h2f_lw_axi_master_agent_read_cp_startofpacket),                 //          .startofpacket
		.sink_endofpacket   (hps_h2f_lw_axi_master_agent_read_cp_endofpacket),                   //          .endofpacket
		.clk                (CLK_clk_clk),                                                       //       clk.clk
		.reset              (HPS_h2f_lw_axi_master_agent_clk_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready          (router_001_src_ready),                                              //       src.ready
		.src_valid          (router_001_src_valid),                                              //          .valid
		.src_data           (router_001_src_data),                                               //          .data
		.src_channel        (router_001_src_channel),                                            //          .channel
		.src_startofpacket  (router_001_src_startofpacket),                                      //          .startofpacket
		.src_endofpacket    (router_001_src_endofpacket)                                         //          .endofpacket
	);

	MP3_PC_mm_interconnect_1_router_002 router_002 (
		.sink_ready         (audioram_s2_agent_rp_ready),                  //      sink.ready
		.sink_valid         (audioram_s2_agent_rp_valid),                  //          .valid
		.sink_data          (audioram_s2_agent_rp_data),                   //          .data
		.sink_startofpacket (audioram_s2_agent_rp_startofpacket),          //          .startofpacket
		.sink_endofpacket   (audioram_s2_agent_rp_endofpacket),            //          .endofpacket
		.clk                (CLK_clk_clk),                                 //       clk.clk
		.reset              (AudioRAM_reset1_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready          (router_002_src_ready),                        //       src.ready
		.src_valid          (router_002_src_valid),                        //          .valid
		.src_data           (router_002_src_data),                         //          .data
		.src_channel        (router_002_src_channel),                      //          .channel
		.src_startofpacket  (router_002_src_startofpacket),                //          .startofpacket
		.src_endofpacket    (router_002_src_endofpacket)                   //          .endofpacket
	);

	altera_merlin_burst_adapter #(
		.PKT_ADDR_H                (29),
		.PKT_ADDR_L                (9),
		.PKT_BEGIN_BURST           (57),
		.PKT_BYTE_CNT_H            (42),
		.PKT_BYTE_CNT_L            (36),
		.PKT_BYTEEN_H              (8),
		.PKT_BYTEEN_L              (8),
		.PKT_BURST_SIZE_H          (52),
		.PKT_BURST_SIZE_L          (50),
		.PKT_BURST_TYPE_H          (54),
		.PKT_BURST_TYPE_L          (53),
		.PKT_BURSTWRAP_H           (49),
		.PKT_BURSTWRAP_L           (43),
		.PKT_TRANS_COMPRESSED_READ (30),
		.PKT_TRANS_WRITE           (32),
		.PKT_TRANS_READ            (33),
		.OUT_NARROW_SIZE           (0),
		.IN_NARROW_SIZE            (1),
		.OUT_FIXED                 (0),
		.OUT_COMPLETE_WRAP         (0),
		.ST_DATA_W                 (85),
		.ST_CHANNEL_W              (2),
		.OUT_BYTE_CNT_H            (36),
		.OUT_BURSTWRAP_H           (49),
		.COMPRESSED_READ_SUPPORT   (1),
		.BYTEENABLE_SYNTHESIS      (1),
		.PIPE_INPUTS               (0),
		.NO_WRAP_SUPPORT           (0),
		.INCOMPLETE_WRAP_SUPPORT   (0),
		.BURSTWRAP_CONST_MASK      (0),
		.BURSTWRAP_CONST_VALUE     (0),
		.ADAPTER_VERSION           ("13.1")
	) audioram_s2_burst_adapter (
		.clk                   (CLK_clk_clk),                                     //       cr0.clk
		.reset                 (AudioRAM_reset1_reset_bridge_in_reset_reset),     // cr0_reset.reset
		.sink0_valid           (audioram_s2_cmd_width_adapter_src_valid),         //     sink0.valid
		.sink0_data            (audioram_s2_cmd_width_adapter_src_data),          //          .data
		.sink0_channel         (audioram_s2_cmd_width_adapter_src_channel),       //          .channel
		.sink0_startofpacket   (audioram_s2_cmd_width_adapter_src_startofpacket), //          .startofpacket
		.sink0_endofpacket     (audioram_s2_cmd_width_adapter_src_endofpacket),   //          .endofpacket
		.sink0_ready           (audioram_s2_cmd_width_adapter_src_ready),         //          .ready
		.source0_valid         (audioram_s2_burst_adapter_source0_valid),         //   source0.valid
		.source0_data          (audioram_s2_burst_adapter_source0_data),          //          .data
		.source0_channel       (audioram_s2_burst_adapter_source0_channel),       //          .channel
		.source0_startofpacket (audioram_s2_burst_adapter_source0_startofpacket), //          .startofpacket
		.source0_endofpacket   (audioram_s2_burst_adapter_source0_endofpacket),   //          .endofpacket
		.source0_ready         (audioram_s2_burst_adapter_source0_ready)          //          .ready
	);

	MP3_PC_mm_interconnect_1_cmd_demux cmd_demux (
		.clk                (CLK_clk_clk),                                                       //       clk.clk
		.reset              (HPS_h2f_lw_axi_master_agent_clk_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (router_src_ready),                                                  //      sink.ready
		.sink_channel       (router_src_channel),                                                //          .channel
		.sink_data          (router_src_data),                                                   //          .data
		.sink_startofpacket (router_src_startofpacket),                                          //          .startofpacket
		.sink_endofpacket   (router_src_endofpacket),                                            //          .endofpacket
		.sink_valid         (router_src_valid),                                                  //          .valid
		.src0_ready         (cmd_demux_src0_ready),                                              //      src0.ready
		.src0_valid         (cmd_demux_src0_valid),                                              //          .valid
		.src0_data          (cmd_demux_src0_data),                                               //          .data
		.src0_channel       (cmd_demux_src0_channel),                                            //          .channel
		.src0_startofpacket (cmd_demux_src0_startofpacket),                                      //          .startofpacket
		.src0_endofpacket   (cmd_demux_src0_endofpacket)                                         //          .endofpacket
	);

	MP3_PC_mm_interconnect_1_cmd_demux cmd_demux_001 (
		.clk                (CLK_clk_clk),                                                       //       clk.clk
		.reset              (HPS_h2f_lw_axi_master_agent_clk_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (router_001_src_ready),                                              //      sink.ready
		.sink_channel       (router_001_src_channel),                                            //          .channel
		.sink_data          (router_001_src_data),                                               //          .data
		.sink_startofpacket (router_001_src_startofpacket),                                      //          .startofpacket
		.sink_endofpacket   (router_001_src_endofpacket),                                        //          .endofpacket
		.sink_valid         (router_001_src_valid),                                              //          .valid
		.src0_ready         (cmd_demux_001_src0_ready),                                          //      src0.ready
		.src0_valid         (cmd_demux_001_src0_valid),                                          //          .valid
		.src0_data          (cmd_demux_001_src0_data),                                           //          .data
		.src0_channel       (cmd_demux_001_src0_channel),                                        //          .channel
		.src0_startofpacket (cmd_demux_001_src0_startofpacket),                                  //          .startofpacket
		.src0_endofpacket   (cmd_demux_001_src0_endofpacket)                                     //          .endofpacket
	);

	MP3_PC_mm_interconnect_1_cmd_mux cmd_mux (
		.clk                 (CLK_clk_clk),                                 //       clk.clk
		.reset               (AudioRAM_reset1_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (cmd_mux_src_ready),                           //       src.ready
		.src_valid           (cmd_mux_src_valid),                           //          .valid
		.src_data            (cmd_mux_src_data),                            //          .data
		.src_channel         (cmd_mux_src_channel),                         //          .channel
		.src_startofpacket   (cmd_mux_src_startofpacket),                   //          .startofpacket
		.src_endofpacket     (cmd_mux_src_endofpacket),                     //          .endofpacket
		.sink0_ready         (cmd_demux_src0_ready),                        //     sink0.ready
		.sink0_valid         (cmd_demux_src0_valid),                        //          .valid
		.sink0_channel       (cmd_demux_src0_channel),                      //          .channel
		.sink0_data          (cmd_demux_src0_data),                         //          .data
		.sink0_startofpacket (cmd_demux_src0_startofpacket),                //          .startofpacket
		.sink0_endofpacket   (cmd_demux_src0_endofpacket),                  //          .endofpacket
		.sink1_ready         (cmd_demux_001_src0_ready),                    //     sink1.ready
		.sink1_valid         (cmd_demux_001_src0_valid),                    //          .valid
		.sink1_channel       (cmd_demux_001_src0_channel),                  //          .channel
		.sink1_data          (cmd_demux_001_src0_data),                     //          .data
		.sink1_startofpacket (cmd_demux_001_src0_startofpacket),            //          .startofpacket
		.sink1_endofpacket   (cmd_demux_001_src0_endofpacket)               //          .endofpacket
	);

	MP3_PC_mm_interconnect_1_rsp_demux rsp_demux (
		.clk                (CLK_clk_clk),                                     //       clk.clk
		.reset              (AudioRAM_reset1_reset_bridge_in_reset_reset),     // clk_reset.reset
		.sink_ready         (audioram_s2_rsp_width_adapter_src_ready),         //      sink.ready
		.sink_channel       (audioram_s2_rsp_width_adapter_src_channel),       //          .channel
		.sink_data          (audioram_s2_rsp_width_adapter_src_data),          //          .data
		.sink_startofpacket (audioram_s2_rsp_width_adapter_src_startofpacket), //          .startofpacket
		.sink_endofpacket   (audioram_s2_rsp_width_adapter_src_endofpacket),   //          .endofpacket
		.sink_valid         (audioram_s2_rsp_width_adapter_src_valid),         //          .valid
		.src0_ready         (rsp_demux_src0_ready),                            //      src0.ready
		.src0_valid         (rsp_demux_src0_valid),                            //          .valid
		.src0_data          (rsp_demux_src0_data),                             //          .data
		.src0_channel       (rsp_demux_src0_channel),                          //          .channel
		.src0_startofpacket (rsp_demux_src0_startofpacket),                    //          .startofpacket
		.src0_endofpacket   (rsp_demux_src0_endofpacket),                      //          .endofpacket
		.src1_ready         (rsp_demux_src1_ready),                            //      src1.ready
		.src1_valid         (rsp_demux_src1_valid),                            //          .valid
		.src1_data          (rsp_demux_src1_data),                             //          .data
		.src1_channel       (rsp_demux_src1_channel),                          //          .channel
		.src1_startofpacket (rsp_demux_src1_startofpacket),                    //          .startofpacket
		.src1_endofpacket   (rsp_demux_src1_endofpacket)                       //          .endofpacket
	);

	MP3_PC_mm_interconnect_1_rsp_mux rsp_mux (
		.clk                 (CLK_clk_clk),                                                       //       clk.clk
		.reset               (HPS_h2f_lw_axi_master_agent_clk_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (rsp_mux_src_ready),                                                 //       src.ready
		.src_valid           (rsp_mux_src_valid),                                                 //          .valid
		.src_data            (rsp_mux_src_data),                                                  //          .data
		.src_channel         (rsp_mux_src_channel),                                               //          .channel
		.src_startofpacket   (rsp_mux_src_startofpacket),                                         //          .startofpacket
		.src_endofpacket     (rsp_mux_src_endofpacket),                                           //          .endofpacket
		.sink0_ready         (rsp_demux_src0_ready),                                              //     sink0.ready
		.sink0_valid         (rsp_demux_src0_valid),                                              //          .valid
		.sink0_channel       (rsp_demux_src0_channel),                                            //          .channel
		.sink0_data          (rsp_demux_src0_data),                                               //          .data
		.sink0_startofpacket (rsp_demux_src0_startofpacket),                                      //          .startofpacket
		.sink0_endofpacket   (rsp_demux_src0_endofpacket)                                         //          .endofpacket
	);

	MP3_PC_mm_interconnect_1_rsp_mux rsp_mux_001 (
		.clk                 (CLK_clk_clk),                                                       //       clk.clk
		.reset               (HPS_h2f_lw_axi_master_agent_clk_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (rsp_mux_001_src_ready),                                             //       src.ready
		.src_valid           (rsp_mux_001_src_valid),                                             //          .valid
		.src_data            (rsp_mux_001_src_data),                                              //          .data
		.src_channel         (rsp_mux_001_src_channel),                                           //          .channel
		.src_startofpacket   (rsp_mux_001_src_startofpacket),                                     //          .startofpacket
		.src_endofpacket     (rsp_mux_001_src_endofpacket),                                       //          .endofpacket
		.sink0_ready         (rsp_demux_src1_ready),                                              //     sink0.ready
		.sink0_valid         (rsp_demux_src1_valid),                                              //          .valid
		.sink0_channel       (rsp_demux_src1_channel),                                            //          .channel
		.sink0_data          (rsp_demux_src1_data),                                               //          .data
		.sink0_startofpacket (rsp_demux_src1_startofpacket),                                      //          .startofpacket
		.sink0_endofpacket   (rsp_demux_src1_endofpacket)                                         //          .endofpacket
	);

	altera_merlin_width_adapter #(
		.IN_PKT_ADDR_H                 (29),
		.IN_PKT_ADDR_L                 (9),
		.IN_PKT_DATA_H                 (7),
		.IN_PKT_DATA_L                 (0),
		.IN_PKT_BYTEEN_H               (8),
		.IN_PKT_BYTEEN_L               (8),
		.IN_PKT_BYTE_CNT_H             (42),
		.IN_PKT_BYTE_CNT_L             (36),
		.IN_PKT_TRANS_COMPRESSED_READ  (30),
		.IN_PKT_TRANS_WRITE            (32),
		.IN_PKT_BURSTWRAP_H            (49),
		.IN_PKT_BURSTWRAP_L            (43),
		.IN_PKT_BURST_SIZE_H           (52),
		.IN_PKT_BURST_SIZE_L           (50),
		.IN_PKT_RESPONSE_STATUS_H      (81),
		.IN_PKT_RESPONSE_STATUS_L      (80),
		.IN_PKT_TRANS_EXCLUSIVE        (35),
		.IN_PKT_BURST_TYPE_H           (54),
		.IN_PKT_BURST_TYPE_L           (53),
		.IN_PKT_ORI_BURST_SIZE_L       (82),
		.IN_PKT_ORI_BURST_SIZE_H       (84),
		.IN_ST_DATA_W                  (85),
		.OUT_PKT_ADDR_H                (56),
		.OUT_PKT_ADDR_L                (36),
		.OUT_PKT_DATA_H                (31),
		.OUT_PKT_DATA_L                (0),
		.OUT_PKT_BYTEEN_H              (35),
		.OUT_PKT_BYTEEN_L              (32),
		.OUT_PKT_BYTE_CNT_H            (69),
		.OUT_PKT_BYTE_CNT_L            (63),
		.OUT_PKT_TRANS_COMPRESSED_READ (57),
		.OUT_PKT_BURST_SIZE_H          (79),
		.OUT_PKT_BURST_SIZE_L          (77),
		.OUT_PKT_RESPONSE_STATUS_H     (108),
		.OUT_PKT_RESPONSE_STATUS_L     (107),
		.OUT_PKT_TRANS_EXCLUSIVE       (62),
		.OUT_PKT_BURST_TYPE_H          (81),
		.OUT_PKT_BURST_TYPE_L          (80),
		.OUT_PKT_ORI_BURST_SIZE_L      (109),
		.OUT_PKT_ORI_BURST_SIZE_H      (111),
		.OUT_ST_DATA_W                 (112),
		.ST_CHANNEL_W                  (2),
		.OPTIMIZE_FOR_RSP              (0),
		.RESPONSE_PATH                 (1),
		.CONSTANT_BURST_SIZE           (0),
		.PACKING                       (1),
		.ENABLE_ADDRESS_ALIGNMENT      (1)
	) audioram_s2_rsp_width_adapter (
		.clk                  (CLK_clk_clk),                                     //       clk.clk
		.reset                (AudioRAM_reset1_reset_bridge_in_reset_reset),     // clk_reset.reset
		.in_valid             (router_002_src_valid),                            //      sink.valid
		.in_channel           (router_002_src_channel),                          //          .channel
		.in_startofpacket     (router_002_src_startofpacket),                    //          .startofpacket
		.in_endofpacket       (router_002_src_endofpacket),                      //          .endofpacket
		.in_ready             (router_002_src_ready),                            //          .ready
		.in_data              (router_002_src_data),                             //          .data
		.out_endofpacket      (audioram_s2_rsp_width_adapter_src_endofpacket),   //       src.endofpacket
		.out_data             (audioram_s2_rsp_width_adapter_src_data),          //          .data
		.out_channel          (audioram_s2_rsp_width_adapter_src_channel),       //          .channel
		.out_valid            (audioram_s2_rsp_width_adapter_src_valid),         //          .valid
		.out_ready            (audioram_s2_rsp_width_adapter_src_ready),         //          .ready
		.out_startofpacket    (audioram_s2_rsp_width_adapter_src_startofpacket), //          .startofpacket
		.in_command_size_data (3'b000)                                           // (terminated)
	);

	altera_merlin_width_adapter #(
		.IN_PKT_ADDR_H                 (56),
		.IN_PKT_ADDR_L                 (36),
		.IN_PKT_DATA_H                 (31),
		.IN_PKT_DATA_L                 (0),
		.IN_PKT_BYTEEN_H               (35),
		.IN_PKT_BYTEEN_L               (32),
		.IN_PKT_BYTE_CNT_H             (69),
		.IN_PKT_BYTE_CNT_L             (63),
		.IN_PKT_TRANS_COMPRESSED_READ  (57),
		.IN_PKT_TRANS_WRITE            (59),
		.IN_PKT_BURSTWRAP_H            (76),
		.IN_PKT_BURSTWRAP_L            (70),
		.IN_PKT_BURST_SIZE_H           (79),
		.IN_PKT_BURST_SIZE_L           (77),
		.IN_PKT_RESPONSE_STATUS_H      (108),
		.IN_PKT_RESPONSE_STATUS_L      (107),
		.IN_PKT_TRANS_EXCLUSIVE        (62),
		.IN_PKT_BURST_TYPE_H           (81),
		.IN_PKT_BURST_TYPE_L           (80),
		.IN_PKT_ORI_BURST_SIZE_L       (109),
		.IN_PKT_ORI_BURST_SIZE_H       (111),
		.IN_ST_DATA_W                  (112),
		.OUT_PKT_ADDR_H                (29),
		.OUT_PKT_ADDR_L                (9),
		.OUT_PKT_DATA_H                (7),
		.OUT_PKT_DATA_L                (0),
		.OUT_PKT_BYTEEN_H              (8),
		.OUT_PKT_BYTEEN_L              (8),
		.OUT_PKT_BYTE_CNT_H            (42),
		.OUT_PKT_BYTE_CNT_L            (36),
		.OUT_PKT_TRANS_COMPRESSED_READ (30),
		.OUT_PKT_BURST_SIZE_H          (52),
		.OUT_PKT_BURST_SIZE_L          (50),
		.OUT_PKT_RESPONSE_STATUS_H     (81),
		.OUT_PKT_RESPONSE_STATUS_L     (80),
		.OUT_PKT_TRANS_EXCLUSIVE       (35),
		.OUT_PKT_BURST_TYPE_H          (54),
		.OUT_PKT_BURST_TYPE_L          (53),
		.OUT_PKT_ORI_BURST_SIZE_L      (82),
		.OUT_PKT_ORI_BURST_SIZE_H      (84),
		.OUT_ST_DATA_W                 (85),
		.ST_CHANNEL_W                  (2),
		.OPTIMIZE_FOR_RSP              (0),
		.RESPONSE_PATH                 (0),
		.CONSTANT_BURST_SIZE           (0),
		.PACKING                       (0),
		.ENABLE_ADDRESS_ALIGNMENT      (1)
	) audioram_s2_cmd_width_adapter (
		.clk                  (CLK_clk_clk),                                     //       clk.clk
		.reset                (AudioRAM_reset1_reset_bridge_in_reset_reset),     // clk_reset.reset
		.in_valid             (cmd_mux_src_valid),                               //      sink.valid
		.in_channel           (cmd_mux_src_channel),                             //          .channel
		.in_startofpacket     (cmd_mux_src_startofpacket),                       //          .startofpacket
		.in_endofpacket       (cmd_mux_src_endofpacket),                         //          .endofpacket
		.in_ready             (cmd_mux_src_ready),                               //          .ready
		.in_data              (cmd_mux_src_data),                                //          .data
		.out_endofpacket      (audioram_s2_cmd_width_adapter_src_endofpacket),   //       src.endofpacket
		.out_data             (audioram_s2_cmd_width_adapter_src_data),          //          .data
		.out_channel          (audioram_s2_cmd_width_adapter_src_channel),       //          .channel
		.out_valid            (audioram_s2_cmd_width_adapter_src_valid),         //          .valid
		.out_ready            (audioram_s2_cmd_width_adapter_src_ready),         //          .ready
		.out_startofpacket    (audioram_s2_cmd_width_adapter_src_startofpacket), //          .startofpacket
		.in_command_size_data (3'b000)                                           // (terminated)
	);

	MP3_PC_mm_interconnect_0_avalon_st_adapter_002 #(
		.inBitsPerSymbol (10),
		.inUsePackets    (0),
		.inDataWidth     (10),
		.inChannelWidth  (0),
		.inErrorWidth    (0),
		.inUseEmptyPort  (0),
		.inUseValid      (1),
		.inUseReady      (1),
		.inReadyLatency  (0),
		.outDataWidth    (10),
		.outChannelWidth (0),
		.outErrorWidth   (1),
		.outUseEmptyPort (0),
		.outUseValid     (1),
		.outUseReady     (1),
		.outReadyLatency (0)
	) avalon_st_adapter (
		.in_clk_0_clk   (CLK_clk_clk),                                 // in_clk_0.clk
		.in_rst_0_reset (AudioRAM_reset1_reset_bridge_in_reset_reset), // in_rst_0.reset
		.in_0_data      (audioram_s2_agent_rdata_fifo_out_data),       //     in_0.data
		.in_0_valid     (audioram_s2_agent_rdata_fifo_out_valid),      //         .valid
		.in_0_ready     (audioram_s2_agent_rdata_fifo_out_ready),      //         .ready
		.out_0_data     (avalon_st_adapter_out_0_data),                //    out_0.data
		.out_0_valid    (avalon_st_adapter_out_0_valid),               //         .valid
		.out_0_ready    (avalon_st_adapter_out_0_ready),               //         .ready
		.out_0_error    (avalon_st_adapter_out_0_error)                //         .error
	);

endmodule
