	MP3_PC u0 (
		.audio_external_BCLK           (<connected-to-audio_external_BCLK>),           //     audio_external.BCLK
		.audio_external_DACDAT         (<connected-to-audio_external_DACDAT>),         //                   .DACDAT
		.audio_external_DACLRCK        (<connected-to-audio_external_DACLRCK>),        //                   .DACLRCK
		.buttons_export_export         (<connected-to-buttons_export_export>),         //     buttons_export.export
		.clk_clk                       (<connected-to-clk_clk>),                       //                clk.clk
		.hps_h2f_mpu_events_eventi     (<connected-to-hps_h2f_mpu_events_eventi>),     // hps_h2f_mpu_events.eventi
		.hps_h2f_mpu_events_evento     (<connected-to-hps_h2f_mpu_events_evento>),     //                   .evento
		.hps_h2f_mpu_events_standbywfe (<connected-to-hps_h2f_mpu_events_standbywfe>), //                   .standbywfe
		.hps_h2f_mpu_events_standbywfi (<connected-to-hps_h2f_mpu_events_standbywfi>), //                   .standbywfi
		.hps_io_hps_io_sdio_inst_CMD   (<connected-to-hps_io_hps_io_sdio_inst_CMD>),   //             hps_io.hps_io_sdio_inst_CMD
		.hps_io_hps_io_sdio_inst_D0    (<connected-to-hps_io_hps_io_sdio_inst_D0>),    //                   .hps_io_sdio_inst_D0
		.hps_io_hps_io_sdio_inst_D1    (<connected-to-hps_io_hps_io_sdio_inst_D1>),    //                   .hps_io_sdio_inst_D1
		.hps_io_hps_io_sdio_inst_CLK   (<connected-to-hps_io_hps_io_sdio_inst_CLK>),   //                   .hps_io_sdio_inst_CLK
		.hps_io_hps_io_sdio_inst_D2    (<connected-to-hps_io_hps_io_sdio_inst_D2>),    //                   .hps_io_sdio_inst_D2
		.hps_io_hps_io_sdio_inst_D3    (<connected-to-hps_io_hps_io_sdio_inst_D3>),    //                   .hps_io_sdio_inst_D3
		.memory_mem_a                  (<connected-to-memory_mem_a>),                  //             memory.mem_a
		.memory_mem_ba                 (<connected-to-memory_mem_ba>),                 //                   .mem_ba
		.memory_mem_ck                 (<connected-to-memory_mem_ck>),                 //                   .mem_ck
		.memory_mem_ck_n               (<connected-to-memory_mem_ck_n>),               //                   .mem_ck_n
		.memory_mem_cke                (<connected-to-memory_mem_cke>),                //                   .mem_cke
		.memory_mem_cs_n               (<connected-to-memory_mem_cs_n>),               //                   .mem_cs_n
		.memory_mem_ras_n              (<connected-to-memory_mem_ras_n>),              //                   .mem_ras_n
		.memory_mem_cas_n              (<connected-to-memory_mem_cas_n>),              //                   .mem_cas_n
		.memory_mem_we_n               (<connected-to-memory_mem_we_n>),               //                   .mem_we_n
		.memory_mem_reset_n            (<connected-to-memory_mem_reset_n>),            //                   .mem_reset_n
		.memory_mem_dq                 (<connected-to-memory_mem_dq>),                 //                   .mem_dq
		.memory_mem_dqs                (<connected-to-memory_mem_dqs>),                //                   .mem_dqs
		.memory_mem_dqs_n              (<connected-to-memory_mem_dqs_n>),              //                   .mem_dqs_n
		.memory_mem_odt                (<connected-to-memory_mem_odt>),                //                   .mem_odt
		.memory_mem_dm                 (<connected-to-memory_mem_dm>),                 //                   .mem_dm
		.memory_oct_rzqin              (<connected-to-memory_oct_rzqin>),              //                   .oct_rzqin
		.pll_vga_locked_export         (<connected-to-pll_vga_locked_export>),         //     pll_vga_locked.export
		.seven_seg_export              (<connected-to-seven_seg_export>),              //          seven_seg.export
		.switchs_export                (<connected-to-switchs_export>),                //            switchs.export
		.vga_controller_CLK            (<connected-to-vga_controller_CLK>),            //     vga_controller.CLK
		.vga_controller_HS             (<connected-to-vga_controller_HS>),             //                   .HS
		.vga_controller_VS             (<connected-to-vga_controller_VS>),             //                   .VS
		.vga_controller_BLANK          (<connected-to-vga_controller_BLANK>),          //                   .BLANK
		.vga_controller_SYNC           (<connected-to-vga_controller_SYNC>),           //                   .SYNC
		.vga_controller_R              (<connected-to-vga_controller_R>),              //                   .R
		.vga_controller_G              (<connected-to-vga_controller_G>),              //                   .G
		.vga_controller_B              (<connected-to-vga_controller_B>),              //                   .B
		.audio_config_SDAT             (<connected-to-audio_config_SDAT>),             //       audio_config.SDAT
		.audio_config_SCLK             (<connected-to-audio_config_SCLK>),             //                   .SCLK
		.audio_pll_clk_clk             (<connected-to-audio_pll_clk_clk>)              //      audio_pll_clk.clk
	);

